### ISSUE TITLE
Travis CI's free plan may run out in the future

### ISSUE THREAD

**Issue by DRJ31** [RainySummerLuo/Blog#1]
You may need to pay for Travis CI in the future because the free travis-ci.org may be shutdown in several weeks, and free plan of travis-ci.com has limited credits which will never refresh. You may run out of those credits if you update your blog for several times. Maybe you should change your continuous integration platform to Github Action or other CI platforms such as CircleCI.

**Comment by RainySummerLuo** [comment]
> 
> 
> You may need to pay for Travis CI in the future because the free travis-ci.org may be shutdown in several weeks, and free plan of travis-ci.com has limited credits which will never refresh. You may run out of those credits if you update your blog for several times. Maybe you should change your continuous integration platform to Github Action or other CI platforms such as CircleCI.

Thanks DRJ, I thought they are free while they are not! So I have checked my credits and there are still plenty enough of them (maybe I rarely update the blog). But anyway thanks for the reminder and I will definitely switch to other free alternatives in the future  after those credits run out ❤️.
